<?php

namespace AppBundle\Repository;

/**
 * Peluqueria_PatientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Peluqueria_PatientRepository extends \Doctrine\ORM\EntityRepository
{
}
