<?php

namespace AppBundle\Repository;

/**
 * PeluqueriaSpecialityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeluqueriaSpecialityRepository extends \Doctrine\ORM\EntityRepository
{
}
