<?php

namespace AppBundle\Repository;

/**
 * PeluqueriaSubSpecilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeluqueriaSubSpecilityRepository extends \Doctrine\ORM\EntityRepository
{
}
