<?php

namespace AppBundle\Repository;

/**
 * SubSpecialityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubSpecialityRepository extends \Doctrine\ORM\EntityRepository
{
}
