app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /api
#    defaults:
#      _format: json
api_login_check:
    path: /api/login_check

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"